### ISSUE TITLE
Make sure we don't have active stripe subscriptions connected with deleted accounts

### ISSUE THREAD

**Issue by interstella-5555** [SkynetLabs/webportal-accounts-dashboard#16]
Good immediate improvement but @ro-tex I think we should cancel the subscription for the user if he deletes the account. I think it should be done inside of the account delete endpoint unless the api is strictly crud-style, otherwise we will need a separate endpoint for this to call from frontend as precondition

_Originally posted by @kwypchlo in https://github.com/SkynetLabs/webportal-accounts-dashboard/pull/14#pullrequestreview-989268852_

**Comment by ro-tex** [comment]
Dup of https://linear.app/skynetlabs/issue/SKY-717/make-sure-stripe-subscription-is-canceled-when-user-deletes-their
